#DO NOT ADD VAR BEFORE FILES

ARM_OBJS+=\
armasmprinter.o\
arm_cg.o\
arm_sim.o\
arm_cgmgr.o\
arm.o\
armir2or.o\
arm_lis.o\
arm_lra.o\
arm_or.o\
arm_passmgr.o\
arm_ramgr.o\
arm_region.o\
arm_region_mgr.o\
arm_scalar_opt.o\
arm_refine.o\
arm_sr.o\
arm_var.o\
arm_ddg.o
