COM_OBJS +=\
$(SRC)/com/ltype.o \
$(SRC)/com/xmat.o \
$(SRC)/com/comf.o \
$(SRC)/com/strbuf.o \
$(SRC)/com/smempool.o \
$(SRC)/com/agraph.o \
$(SRC)/com/sgraph.o \
$(SRC)/com/rational.o \
$(SRC)/com/birational.o \
$(SRC)/com/bigint.o \
$(SRC)/com/flty.o \
$(SRC)/com/linsys.o \
$(SRC)/com/diagnostic.o \
$(SRC)/com/bs.o\
$(SRC)/com/scc.o\
$(SRC)/com/sbs.o\
$(SRC)/com/sort.o\
$(SRC)/com/byteop.o\
$(SRC)/com/rpo.o\
$(SRC)/com/tree.o\
$(SRC)/com/domtree.o\
$(SRC)/com/lca.o
