COM_OBJS +=\
../com/ltype.o \
../com/xmat.o \
../com/comf.o \
../com/strbuf.o \
../com/smempool.o \
../com/agraph.o \
../com/sgraph.o \
../com/rational.o \
../com/birational.o \
../com/bigint.o \
../com/flty.o \
../com/linsys.o \
../com/diagnostic.o \
../com/bs.o\
../com/scc.o
