#DO NOT ADD VAR BEFORE FILES

COM_OBJS+=\
ltype.o\
xmat.o\
comf.o\
strbuf.o\
smempool.o\
agraph.o\
sgraph.o\
rational.o\
birational.o\
bigint.o\
flty.o\
linsys.o\
bs.o\
log.o\
numdiff.o\
scc.o\
sbs.o\
sort.o\
byteop.o\
rpo.o\
tree.o\
domtree.o\
lca.o\
assemblebin.o\
fileobj.o\
xtensor.o\
diagnostic.o

COM_OUTPUT=libxcom.a
