CFE_OBJS +=\
../cfe/decl.o\
../cfe/err.o\
../cfe/exectree.o\
../cfe/lex.o\
../cfe/scope.o\
../cfe/st.o\
../cfe/tree.o\
../cfe/treegen.o\
../cfe/typeck.o\
../cfe/cfeutil.o\
../cfe/declinit.o\
../cfe/typetran.o\
../cfe/cell.o
